version: '3.8'

services:
  api:
    build: .
    container_name: blog-api
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=localhost
      - DB_DATABASE=blog
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    depends_on:
      - db
volumes:
  pgdata: