name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Instalar Docker Compose (compatibilidade)
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Subir DB
      run: docker-compose up -d db

    - name: Esperar DB estar disponível (PostgreSQL)
      run: |
        echo "Aguardando PostgreSQL aceitar conexões..."
        until docker-compose exec -T db pg_isready -U postgres; do
          sleep 2
        done

    - name: Rodar migrations
      run: docker-compose run --rm api npm run migrate

    - name: Rodar testes
      run: docker-compose run --rm api npm test

    - name: Gerar cobertura
      run: docker-compose run --rm api npm run coverage

    - name: Estabelecendo conexão SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

    - name: Deploy na VPS via SSH
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          cd /home/ubuntu/devtools/blog-api || exit 1
          git pull origin main
          docker-compose pull
          docker-compose up -d --build
        EOF
