name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Estabelecer conexão SSH com VPS
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy remoto via SSH na VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            set -e

            if [ ! -d /home/ubuntu/devtools/blog-api/.git ]; then
              echo '[INFO] Clonando repositório'
              git clone https://github.com/leograva/blog-api.git /home/ubuntu/devtools/blog-api
            else
              echo '[INFO] Repositório já existe, atualizando'
              cd /home/ubuntu/devtools/blog-api
              git fetch --all
              git reset --hard origin/main
            fi

            cd /home/ubuntu/devtools/blog-api
            echo '[INFO] Verificando package.json'
            ls -l package.json

            echo '[INFO] Atualizando imagens Docker'
            docker compose pull

            echo '[INFO] Recriando containers com build'
            docker compose up -d --build
          "